FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-libav \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer-plugins-good1.0-0 \
    libgstreamer-plugins-bad1.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN cd /opt/ &&\
    git clone git://anongit.freedesktop.org/gstreamer/gst-rtsp-server && cd gst-rtsp-server &&\
    git checkout remotes/origin/1.2 &&\
    ./autogen.sh --noconfigure && GST_PLUGINS_GOOD_DIR=$(pkg-config --variable=pluginsdir gstreamer-plugins-bad-1.0) ./configure && make cd examples 

ENV UDP_ADDR=0.0.0.0
ENV UDP_PORT=5000
ENV GST_OMX_CONFIG_DIR=/usr/lib/arm-linux-gnueabihf/gstreamer-1.0

WORKDIR /app
CMD ./test-launch "(videotestsrc ! videoconvert ! video/x-raw,format=RGB ! rtpvrawpay !)"

