FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3.6 \
    cmake \
    make \
    wget \
    git \
    ffmpeg \
    python3-pip\
    python3-opencv\
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone https://github.com/rgaufman/live555.git &&\ 
    cd live555 &&\
    ./genMakefiles linux-64bit &&\
    make &&\
    cd mediaServer &&\
    wget https://c7xcode.obs.cn-north-4.myhuaweicloud.com/models/YOLOV4_coco_detection_car_video/test_video/test.mp4 &&\
    ffmpeg -i test.mp4 -codec copy -bsf: h264_mp4toannexb -f h264 test.264 &&\
    wget http://www.live555.com/liveMedia/public/264/slamtv60.264

WORKDIR /opt/live555/mediaServer
CMD /opt/live555/mediaServer/live555MediaServer  
